### PR TITLE
Migrate documentation from Markdown to AsciiDocs (multibook part)

### PR DESCRIPTION
**Pull request by Mikejmnez**
This PR will complete the migration of the DAP4 specification from Markdown to AsciiDoc. Before merging this PR, the following items need to be completed:

- [x] Convert all md files in this repo to ascii doc.
- [x] Create a Root adoc document (named `DAP4.adoc`) that allows `asciidoctor` to build multi-part book with the present adoc files, similar to that of the [Hyrax_Guide](https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.html). Test locally to make sure things look good.
- [x] Re-write all tables, math, and url/href so that these are consistent and are not broken.
- [x] Cross-compare the md files in this repo with the source material (docs.opendap.org) and make sure there is no missing content.
- [x] Set up a travis workflow to build and publish the documentation on gh-pages.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
What is the purpose of this change?

**Comment by ndp-opendap** [comment]
Hi @DennisHeimbigner,

Miguel is working on completing the migration of the specification from our defunct MediaWiki site to GitHub. When Alex started this a few years ago we got the bare bones documents, butnothing worked correctly - all of the documents in GitHub linked out to the MediaWiki and there was no github-io integration . This meant that, in effect, the MediaWiki has continued to be the home of the specification. In order to get the specification integrated into GitHub Miguel is fixing (the links) and reorganizing the content so that it works correctly in GitHub and also so that it can be built/rendered using github-io.

**Comment by DennisHeimbigner** [comment]
Sigh! So this means we need to learn yet another markup language in order to submit pull requests.
I know that what I say will have no impact, but one of the big lessons I have learned from both thredds and
netcdf-c is to minimize the amount of infrastructure tools on which you depend. I now spend more time
debugging infrastructure than I do writing code. Oh well.

**Review by ndp-opendap — COMMENTED** [review]
- Where can I see the GitHub Pages result?

- Or is that a thing that only happens when the merge/commit is made to master?

**Comment by Mikejmnez** [comment]
> * Is that a thing that only happens when a merge/commit is made to the main branch?

Yes - the build process will be done by Travis once it is merged.

> * Where can I see the GitHub Pages result?

If it helps I can add the html that one gets when building locally.

**Review by ndp-opendap — APPROVED** [review]
It looks good. It rendered as HTML on my local system,
I think that this could be merged now. If there are additional structural/formatting changes we can address those if/when they're needed.

**Pull request merged**
